data1 <-read.csv("D:/tempandq.csv")
data1.ts = ts(data=data1$q,start=c(2006,01,01), frequency=370)
data1.ts
library("tseries")
summary(mo1<-arma(data1.ts, order=c(1,1)))
kpss.test(data1.ts)
plot(data1.ts,type="b",main="ARMA(1,1) Model")
lines(fitted(mo1),col="red",lty=6,lwd=2)
install.packages("timsac")
library(timsac)
autoarmafit(data1.ts)
summary(am1<-auto.arima(data1.ts))
plot(forecast(am1))
title("\n \n Time Series Data : data1.ts")
lines(fitted(am1), col="red", lty=2, lwd=2)
plot(data1.ts, main="data1 : Fitted Values")
lines(fitted(forecast(am1),h=1),col=3)
lines(fitted(forecast(am1),h=2),col=2)
legend("topleft",legend=paste("h=",1:2),col=3:2,lty=1)
s1=simulate(am1,8)
s2=simulate(am1,8,bootstrap = T)
plot(data1.ts,xlim=c(2006,2021), main="data1 : Simulation")
lines(s1, col="red", lwd=2)
lines(s2, col="blue", lwd=2, lty=1)
legend("topleft", legend=c("simulation","bootstrap"),col=c(2,4),lty = 1)
